---
title: "A Hopeful Guide to Navigating Spinal Injury: Our Family's Experience at ISIC"
author: "Pratyush Sinha"
date: "2025-01-09"
categories: [Personal Experiences]
draft: False
---

My father has had two major surgeries in the neck at the Indian Spinal Injury Center, and both have been successful. But this post isn’t just about that. I want this post to give you hope that there is a hospital which could really help you in case you suffer from a spine injury. The world does not turn into a bleak place.
Please treat this as a general playbook from one family to another, not as medical advice. Anything I mention that sounds like medical advice here should be discussed with your own doctors.

## The main leverage is time
Time is of the essence when dealing with spinal injuries. The progression of these injuries is rapid and can lead to significant deterioration within a short period, often no more than 10 days to reach a critical stage. Spinal injuries follow an almost exponential curve of decline if not addressed promptly.

Initial symptoms may include a loss of balance, followed by numbness in the fingers and legs. This can then progress to a lack of coordination in the legs, causing a limping gait. In advanced stages, individuals may lose motor functions and control over bladder and bowel movements, leading to a profound loss of confidence. My father experienced this severe stage during his first spinal injury.

Fortunately, we were able to intervene earlier during his second injury. It is crucial to understand that this deterioration can occur within 1 to 3 days. A fall can significantly accelerate this process. Therefore, it is vital not to underestimate the severity of these injuries and to prevent misdiagnosis. My father’s initial symptoms were mistakenly attributed to diabetes.

## We are in the same boat you and I
Indian Healthcare for all its pros and cons is working like an engine. There are great hospitals near Delhi which are semi private. ISIC is one of them.  You could go to AIMS for spinal injuries. But I would suggest against that. The reason is the backlog that AIMS has. No doubt, AIMS is the most affordable. It has probably the best doctors from India. But I think ISIC does a reasonable job of maintaining the balance between cost and good service. I don’t want to delve into past laurels because they are pretty much useless when it comes to the present day running of the hospital but ISIC runs smoothly. If you have Insurance they will be happy to take you in. I did not deal in cash but cash processing is also smooth judging by the queue. 


## Overcoming the surgery
One of the best things about this hospital is its rehabilitation unit. It is where the post-operative care happens, and this is not treated as an add-on; it is considered part of the treatment. All of the people I interacted with were very patient with patients. They would answer all your questions. My father was able to walk after 2 months of the surgery. I consider this to be a miracle of sorts.
I think the hospital staff does a lot of things really well, but there is little being done to ensure transparency between departments. The doctors are transparent, but they do not always help the nursing staff explain their decisions. This leads to confusion for the attendants. The ICU times are perfect and do not need change. The hospital even gave me some slack for feeding my father without the nurse, which I am incredibly grateful for.
Insurance paperwork is really a pain and there are 6 desks to visit. For an attendant, it may seem overwhelming. It is streamlined and people are really helpful, but from day 1, the paperwork seems like a lot. My only benchmark is Max Gurgaon near the Huda Metro Station where the paperwork is just a few signatures. But the positive is everyone tries to help. The staff in the Admissions office help you even if they are non-chalant

----------

## A practical guide to attendants
- Coffee at the main cafeteria is expensive. Go to the retail store and they will sell you the same coffee for cheap. I needed a lot of coffee.
- Junior doctors are your friends. Please listen to them
- Guards are better in the night than during the day
- Have good relations with the nurses, they do more paperwork in a day than what you do in a year. They will help you when you need it. Don’t ask for your test results from them because the doctor is supposed to inform you of that. If the doctors become of aware of this, nurses get a stick from the head nurse
- Whatever games you are thinking that the hospital is playing to increase your bills, it is not
- ICU is Intensive Care Unit. Avoid touching anything and use copious amounts of hand sanitizer if you must touch something
- HDU  is a High Dependency Unit. This is confusing to a lot of the patients. This means that the patient is out of danger but still needs active monitoring. The timings of visit are different from ICU. But rules are the same as the ICU. The doctor is there during visiting times to give you updates. 
- Do not get nurses in trouble with the doctors 
- Floor managers are there for assessing the arrangements. Please do not use them to get your way because they are the admin
- If you are the sole attendant and there is no place to sleep, the best place is your car or near the emergency beside the Cafe Coffee Day. Do not go the attendant’s ward because that place is likely to be filled and is a den of mosquitos


## Closing Notes
There are diseases which you think do not make sense but you need to make sense of them. Spine injuries are one of them. Between these surgeries I have spent a month in the hospital. These are the toughest times you can endure. If anything, I want you to remember that you are in safe hands. Please trust your primary team and do not self medicate. I hope if you are looking for hope. This may be one.


