---
title: "Movie Review: Nayak - the Real hero by Satyajeet Ray"
author: "Pratyush Sinha"
date: "2025-04-08"
categories: [Movie Reviews]
draft: True
---

I am a swucker for movies. I don't like these rowdy movies - Saiyaara, Houseful 5. These are the kind of movies. I don't think movies should be crass. They should be reflective of the times around us.
I would not consider myself a movie critic in any way. However there is a movie I watched recently that made me think that I could be one. If I get a  chance, I will write about that. 
----------

Nayak the hero has a newer version starring Anil Kapoor. This review is not about that. This is about the great Satyajit Ray. 
I have read about him and his movie Pather Panchali but never had a chance to actually see any of his work. This was his first work.

-----------
Nayak is about an actor who is troubled by his dreams. If you look at his work, he tells the story about Bengal. Throughout the movie, whatever was said is still to this day true. 
This amy have been a progressive movie for Bengal. There are a few instances which stood out through out the movie
- The actor travels in first class and is met with a lot of fanfare at both the destinations
- The actors blame people for not watching his moviews
- Movies used to last and were given a lot of time on the screen. In today's world, movies are made for weekends, then it was month's
- In terms of dignity, stage >> advertising >> movies
- In terms of moview, movies >> stage >> advertising

Sharmila Tagore interviews Uttam Kumar and sees his life a little more closely which makes her decide not to publish the interview.
There were three chapters in hero's life which felt really close to the heart.
- Arindam Mukherjee had a stage mentor Sankar Da who does not want Arinday to leave stage for movies. Arindam obliges but Sankar Da dies before the play has its premiere. Arindam decides to go to the movies but Sankar Da haunts him in his dreams. That entire scene of Arindam being happy at all the money being thrown at him and then sinking and not being helped by Sankar Da is very iconoclastic 
- The next is the scene with his long time friend who is a labor's union leader. His friend wants Arindam to lead from the front but he does not. Even when Arindam does get famous, Arindam does not have the courage to address them
- The third scene is probably the most painful one. Arindam is relatively new to acting in films and is humiliated on the sets by a senior actor. Later, when Arindam climbs up he is visited by this senior actor as a frail human being. The whole movie is very well shot.

There is one more scene which is probably amazing to look at and is more significant. Arindam to get back to sleep drinks on the train and is looking out of the tracks. Tracks which are glistened by a light spark following the tracks. I have spent a considerable weekends in my childhood train travelling back and forth and this was something that I observed during all parts of the train. That light on the track follows.