
---
title: "Weekly Updates - 12/2025"
author: "Pratyush Sinha"
date: "2025-03-23"
categories: [Weekly Updates, life]
---

I have been away lately. Having a new born is not easy. My wife* had a baby last year :-) and the first 6 months were really demanding for her. Maternity leave was an easy time to visit our parents for long stretches of time. 

We shifted from Gurgaon to Patna for a couple of months and then to Hazaribagh,my wife's hometown, later. The last week was our last week in Hazaribagh. 

Hazaribagh, as a town is a very quiet place to live in. Actually every place is a quiet to live in considering my lifestyle of not participating in other people's lives. 
Hazaribagh was a hill station once or may it be still is. The recent rise in temperature has shown that hill stations are not hill stations any more. It does not have too many attractions per se and that may have helped preserve its beauty. It has a hill, a very big lake with numerous smaller ones adjacent to it, and is blessed with lush greenery. The clear winner among the three was the lake. It is huge in size and can be captivating in sunsets. It nestles a lot of birds who keep on chirping. 


A few more thoughts which popped:

- I used to think Diversity hirings were not fair. But then again life itself is not fair. I will borrow from the wisdom of people who are wiser than me. I saw 4 women change the course of their lives becacuse of their family. It made me think whether life was really worth it.
- Team management is a tough. People find reasons to not be accountable. Everyday there is a new issue and trust as a manager cannot be given. It needs to be earnt.
- Having smaller routines is probably a good idea. I basically put all these points as notes on Whatsapp and have fleshed out the ideas more here.
- The difference between great and best is the ability to go through the same thing again and again without getting bored. That is how you gain perfection. 

Things I think I could write a blog about: 
1. Indian healthcare system is following the same trajectory as the US. May be documentign what is about to come would be a good idea
2. Document all agents we have seen recently especially from Adobe & SalesForce. 
3. Document all the blogs that I read in the last week


*Before you think this not to be right words I would like you to consider a few ablations that I had tried. 
When I said - My wife and I had a baby, my MD asked what my contribution to the baby was. To be honest, my contribution does not compare ,much to hers but I was there. Anyways, I have come to these choice of words because it works if I say it with a smile.